### ISSUE TITLE
The mechanics of proof について

### ISSUE THREAD

**Issue by Seasawher** [aconite-ac/how_to_install_lean#4]
https://aconite-ac.github.io/how_to_install_lean/lake-package-manager/how-to-use-existing-project.html#%E3%81%8A%E3%81%99%E3%81%99%E3%82%81%E3%81%AElean%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E6%95%99%E6%9D%90

上記で [The mechanics of proof](https://github.com/hrmacbeth/math2001) を紹介されていますが，この教材は mathlib4 と微妙に違うタクティクを独自に開発して使用しているため，そのことについて注意があるとよいと思います．

**Comment by aconite-ac** [comment]
ご提案ありがとうございます。

節「[おすすめのLeanプロジェクト教材](https://aconite-ac.github.io/how_to_install_lean/lake-package-manager/how-to-use-existing-project.html#%E3%81%8A%E3%81%99%E3%81%99%E3%82%81%E3%81%AElean%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E6%95%99%E6%9D%90)」において、各教材の説明文を追加し、
[The mechanics of proof](https://github.com/hrmacbeth/math2001) 独自のタクティクに関する注意も掲載しました。
